/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Aplicacion;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author federico
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    public MenuPrincipal(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegistro = new javax.swing.JToggleButton();
        BotonMostrar = new javax.swing.JToggleButton();
        BotonEliminar = new javax.swing.JToggleButton();
        BotonCalcular = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        BotonTodo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setForeground(new java.awt.Color(51, 102, 255));

        BotonRegistro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotonRegistro.setText("Registrar");
        BotonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonRegistroMouseReleased(evt);
            }
        });

        BotonMostrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotonMostrar.setText("Mostrar");
        BotonMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonMostrarMouseReleased(evt);
            }
        });

        BotonEliminar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonEliminarMouseReleased(evt);
            }
        });

        BotonCalcular.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotonCalcular.setText("Calcular");
        BotonCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonCalcularMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("¿Qué deseas hacer con los datos del alumno?");

        BotonTodo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        BotonTodo.setText("Mostrar Todo");
        BotonTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BotonTodoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistro)
                    .addComponent(BotonCalcular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonMostrar)
                    .addComponent(BotonEliminar))
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(BotonTodo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonRegistro)
                    .addComponent(BotonMostrar))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCalcular)
                    .addComponent(BotonEliminar))
                .addGap(27, 27, 27)
                .addComponent(BotonTodo)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistroMouseReleased
        // TODO add your handling code here:
        dispose();
        Registro A=new Registro();
        A.setVisible(true);
        
    }//GEN-LAST:event_BotonRegistroMouseReleased

    private void BotonMostrarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMostrarMouseReleased
        // TODO add your handling code here:
        dispose();
        Muestra D=new Muestra();
        D.setVisible(true);
    }//GEN-LAST:event_BotonMostrarMouseReleased

    private void BotonCalcularMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCalcularMouseReleased
        // TODO add your handling code here:
        dispose();
         Muestra D=new Muestra();
        D.setVisible(true);
        
    }//GEN-LAST:event_BotonCalcularMouseReleased

    private void BotonTodoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTodoMouseReleased
        // TODO add your handling code here:
        dispose();
        Pantalla D=new Pantalla();
        D.setVisible(true);
        
        
    }//GEN-LAST:event_BotonTodoMouseReleased

    private void BotonEliminarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonEliminarMouseReleased
        dispose();
         Muestra D=new Muestra();
        D.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_BotonEliminarMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonCalcular;
    private javax.swing.JToggleButton BotonEliminar;
    private javax.swing.JToggleButton BotonMostrar;
    private javax.swing.JToggleButton BotonRegistro;
    private javax.swing.JToggleButton BotonTodo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
