/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Aplicacion;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author federico
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarpantalla = new javax.swing.JTextArea();
        regresarmenu = new javax.swing.JButton();
        muestratodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mostrarpantalla.setEditable(false);
        mostrarpantalla.setColumns(20);
        mostrarpantalla.setRows(5);
        jScrollPane1.setViewportView(mostrarpantalla);

        regresarmenu.setText("Menu Principal");
        regresarmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                regresarmenuMouseReleased(evt);
            }
        });

        muestratodo.setText("Mostrar todo");
        muestratodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                muestratodoMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(regresarmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(muestratodo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regresarmenu)
                    .addComponent(muestratodo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarmenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarmenuMouseReleased

        dispose();
        MenuPrincipal D=new MenuPrincipal();
        D.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_regresarmenuMouseReleased

    private void muestratodoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_muestratodoMouseReleased
      
        try{
            int tamRegistro=220;
            int cantRegistros;
            int x=0;
            String alumno="";
            String completo="";
            String completo2="";
            String punto="";
                RandomAccessFile ArchivoAlumno= new RandomAccessFile("DatosAlumno.dat", "rw");
                int tamArchivo=(int) ArchivoAlumno.length();
                cantRegistros= (tamArchivo/tamRegistro);
        if(cantRegistros>0){
           for (int Posicion=0; Posicion<cantRegistros; Posicion++){
           ArchivoAlumno.seek(Posicion*tamRegistro);
                for (int i=0; i<108; i++){
                   alumno= alumno + ArchivoAlumno.readChar(); 
                }
                    x= ArchivoAlumno.readInt();
                    punto=Integer.toString(x);
                   
                completo= alumno + punto;
                completo2= completo2 + "\n" + completo;
                completo="";
                alumno="";
                punto="";
                
           }
                mostrarpantalla.setText(completo2);
        }else mostrarpantalla.setText("No hay alumnos en el registro");
        
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      // TODO add your handling code here:
    }//GEN-LAST:event_muestratodoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mostrarpantalla;
    private javax.swing.JButton muestratodo;
    private javax.swing.JButton regresarmenu;
    // End of variables declaration//GEN-END:variables
}
